skills = {
    "Care of animals": [
        "Agriculture (keeping livestock)",
        "Aquarium keeping",
        "Beekeeping",
        "Caring for reptiles",
        "Dog training & handling",
        "Horse/donkey/llama/alpaca handling & care",
        "Looking after birds (i.e. budgies & canaries)",
        "Pet care \u2013 health/training/maintenance",
        "Pigeon breeding & racing",
    ],
    "Creative arts": [
        "Basket making",
        "Boat work",
        "Brass rubbing",
        "Building catapult & trebuchets",
        "Cake decoration",
        "Camping gear making",
        "Candle-making",
        "Canoe building",
        "Canvas work",
        "Carnival/festival float construction",
        "Ceramics",
        "Clay modelling",
        "Crocheting",
        "Cross stitch",
        "DIY",
        "Dough craft",
        "Drawing",
        "Dressmaking",
        "Egg decorating",
        "Embroidery",
        "Enamelling",
        "Fabric printing",
        "Feng Shui",
        "Floral decoration",
        "French polishing",
        "Furniture restoration",
        "Glass blowing",
        "Glass painting",
        "Interior design",
        "Jewellery making",
        "Knitting",
        "Lace making",
        "Leather work",
        "Lettering & calligraphy",
        "Macram\u00e9",
        "Marquetry",
        "Model construction",
        "Mosaic",
        "Painting & design",
        "Patchwork",
        "Photography",
        "Pottery",
        "Quilting",
        "Rope work",
        "Rug making",
        "Soft toy making",
        "Tatting",
        "Taxidermy",
        "Textiles",
        "Weaving and spinning",
        "Wine/beer making",
        "Woodwork",
    ],
    "Games & recreation": [
        "Cards (i.e. bridge)",
        "Chess",
        "Clay target shooting",
        "Coxing",
        "Cycle maintenance",
        "Darts",
        "Dominoes",
        "Fishing/fly fishing",
        "Flying",
        "Gliding",
        "Go-karting",
        "Historical period re-enacting",
        "Kite construction & flying",
        "Mah Jongg",
        "Marksmanship",
        "Model construction & racing",
        "Motor sports",
        "Power boating",
        "Snooker, pool & billiards",
        "Sports appreciation",
        "Sports leadership",
        "Sports officiating",
        "Table games",
        "War games",
    ],
    "Learning & collecting": [
        "Aeronautics",
        "Aircraft recognition",
        "Anthropology",
        "Archaeology",
        "Astronautics",
        "Astronomy",
        "Bird watching",
        "Coastal navigation",
        "Coins",
        "Collections, studies & surveys",
        "Comics",
        "Contemporary legends",
        "Costume study",
        "Criminology",
        "Dowsing & divining",
        "Fashion",
        "Forces insignia",
        "Gemstones",
        "Genealogy",
        "Heraldry",
        "History of art",
        "Language skills",
        "Military history",
        "Movie posters",
        "Postcards",
        "Reading",
        "Religious studies",
        "Ship recognition",
        "Stamp collecting",
    ],
    "Life skills": [
        "Alternative therapies",
        "Car/Motorcycle maintenance & road skills",
        "Cookery",
        "Democracy in action",
        "Digital lifestyle",
        "Event planning",
        "First aid \u2013 St John/St Andrew/BRCS",
        "Hair & beauty",
        "Learning about the RNLI (Lifeboats)",
        "Learning about the emergency services",
        "Library & information skills",
        "Life skills",
        "Massage",
        "Money management",
        "Navigation",
        "Public speaking and debating",
        "Skills for employment",
        "Young Enterprise",
    ],
    "Media & communication": [
        "Amateur radio",
        "Blogging",
        "Communicating with people who are visually impaired",
        "Communicating with people who have a hearing impediment",
        "Film & video making",
        "Journalism",
        "Newsletter & magazine production",
        "Signalling",
        "Vlogging",
        "Writing",
    ],
    "Music": [
        "Church bell ringing",
        "Composing",
        "DJing",
        "Evaluating music & musical performances",
        "Hand bell ringing",
        "Improvising melodies",
        "Listening to, analysing & describing music",
        "Music appreciation",
        "Playing a musical instrument",
        "Playing in a band",
        "Reading & notating music",
        "Understanding music in relation to history & culture",
    ],
    "Natural world": [
        "Agriculture",
        "Conservation",
        "Forestry",
        "Gardening",
        "Groundsmanship",
        "Growing carnivorous plants",
        "Plant growing",
        "Snail farming",
        "Vegetable growing",
    ],
    "Performance arts": [
        "Ballet appreciation",
        "Ceremonial drill",
        "Circus skills",
        "Conjuring & magic",
        "Majorettes",
        "Puppetry",
        "Singing",
        "Speech & drama",
        "Theatre appreciation",
        "Ventriloquism",
        "Yoyo extreme",
    ],
    "Science & technology": [
        "Aerodynamics",
        "Anatomy",
        "App design",
        "Astronomy",
        "Biology",
        "Botany",
        "Chemistry",
        "Coding/ programming",
        "Ecology",
        "Electronics",
        "Engineering",
        "Entomology",
        "IT",
        "Marine biology",
        "Oceanography",
        "Paleontology",
        "Physics",
        "Rocket making",
        "Taxonomy",
        "Weather/meteorology",
        "Website design",
        "Zoology",
    ],
}

skills_flat = [skill for skill_group in skills.values() for skill in skill_group]
