-- information model version 1

CREATE SCHEMA IF NOT EXISTS v1;

CREATE TABLE IF NOT EXISTS v1.volunteer
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    given_name  TEXT NOT NULL,
    family_name TEXT NOT NULL,
    email       TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS v1.skill
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS v1.volunteer_skill
(
    volunteer_id INT NOT NULL,
    skill_id     INT NOT NULL,
    PRIMARY KEY (volunteer_id, skill_id),
    FOREIGN KEY (volunteer_id) REFERENCES v1.volunteer (id),
    FOREIGN KEY (skill_id) REFERENCES v1.skill (id)
);

CREATE OR REPLACE VIEW v1.volunteer_skills AS (
    SELECT v.given_name || ' ' || v.family_name AS volunteer, s.name AS skill
    FROM v1.volunteer_skill vs
             JOIN v1.volunteer v ON vs.volunteer_id = v.id
             JOIN v1.skill s ON vs.skill_id = s.id
);
